/* soapClient.cpp
   Generated by gSOAP 2.8.11 from tempfForZip.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.11 2012-11-20 18:33:50 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__NDFDgen(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::string latitude, std::string longitude, enum ns2__productType product, time_t startTime, time_t endTime, enum ns2__unitType Unit, ns2__weatherParametersType *weatherParameters, std::string &dwmlOut)
{	struct ns1__NDFDgen soap_tmp_ns1__NDFDgen;
	struct ns1__NDFDgenResponse *soap_tmp_ns1__NDFDgenResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php";
	if (!soap_action)
		soap_action = "http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgen";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__NDFDgen.latitude = latitude;
	soap_tmp_ns1__NDFDgen.longitude = longitude;
	soap_tmp_ns1__NDFDgen.product = product;
	soap_tmp_ns1__NDFDgen.startTime = startTime;
	soap_tmp_ns1__NDFDgen.endTime = endTime;
	soap_tmp_ns1__NDFDgen.Unit = Unit;
	soap_tmp_ns1__NDFDgen.weatherParameters = weatherParameters;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__NDFDgen(soap, &soap_tmp_ns1__NDFDgen);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__NDFDgen(soap, &soap_tmp_ns1__NDFDgen, "ns1:NDFDgen", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__NDFDgen(soap, &soap_tmp_ns1__NDFDgen, "ns1:NDFDgen", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&dwmlOut)
		return soap_closesock(soap);
	soap_default_std__string(soap, &dwmlOut);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__NDFDgenResponse = soap_get_ns1__NDFDgenResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	dwmlOut = soap_tmp_ns1__NDFDgenResponse->dwmlOut;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__NDFDgenByDay(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::string latitude, std::string longitude, std::string startDate, std::string numDays, enum ns2__unitType Unit, enum ns2__formatType format, std::string &dwmlByDayOut)
{	struct ns1__NDFDgenByDay soap_tmp_ns1__NDFDgenByDay;
	struct ns1__NDFDgenByDayResponse *soap_tmp_ns1__NDFDgenByDayResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php";
	if (!soap_action)
		soap_action = "http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgenByDay";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__NDFDgenByDay.latitude = latitude;
	soap_tmp_ns1__NDFDgenByDay.longitude = longitude;
	soap_tmp_ns1__NDFDgenByDay.startDate = startDate;
	soap_tmp_ns1__NDFDgenByDay.numDays = numDays;
	soap_tmp_ns1__NDFDgenByDay.Unit = Unit;
	soap_tmp_ns1__NDFDgenByDay.format = format;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__NDFDgenByDay(soap, &soap_tmp_ns1__NDFDgenByDay);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__NDFDgenByDay(soap, &soap_tmp_ns1__NDFDgenByDay, "ns1:NDFDgenByDay", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__NDFDgenByDay(soap, &soap_tmp_ns1__NDFDgenByDay, "ns1:NDFDgenByDay", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&dwmlByDayOut)
		return soap_closesock(soap);
	soap_default_std__string(soap, &dwmlByDayOut);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__NDFDgenByDayResponse = soap_get_ns1__NDFDgenByDayResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	dwmlByDayOut = soap_tmp_ns1__NDFDgenByDayResponse->dwmlByDayOut;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__NDFDgenLatLonList(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::string listLatLon, enum ns2__productType product, time_t startTime, time_t endTime, enum ns2__unitType Unit, ns2__weatherParametersType *weatherParameters, std::string &dwmlOut)
{	struct ns1__NDFDgenLatLonList soap_tmp_ns1__NDFDgenLatLonList;
	struct ns1__NDFDgenLatLonListResponse *soap_tmp_ns1__NDFDgenLatLonListResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php";
	if (!soap_action)
		soap_action = "http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgenLatLonList";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__NDFDgenLatLonList.listLatLon = listLatLon;
	soap_tmp_ns1__NDFDgenLatLonList.product = product;
	soap_tmp_ns1__NDFDgenLatLonList.startTime = startTime;
	soap_tmp_ns1__NDFDgenLatLonList.endTime = endTime;
	soap_tmp_ns1__NDFDgenLatLonList.Unit = Unit;
	soap_tmp_ns1__NDFDgenLatLonList.weatherParameters = weatherParameters;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__NDFDgenLatLonList(soap, &soap_tmp_ns1__NDFDgenLatLonList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__NDFDgenLatLonList(soap, &soap_tmp_ns1__NDFDgenLatLonList, "ns1:NDFDgenLatLonList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__NDFDgenLatLonList(soap, &soap_tmp_ns1__NDFDgenLatLonList, "ns1:NDFDgenLatLonList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&dwmlOut)
		return soap_closesock(soap);
	soap_default_std__string(soap, &dwmlOut);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__NDFDgenLatLonListResponse = soap_get_ns1__NDFDgenLatLonListResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	dwmlOut = soap_tmp_ns1__NDFDgenLatLonListResponse->dwmlOut;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__NDFDgenByDayLatLonList(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::string listLatLon, std::string startDate, std::string numDays, enum ns2__unitType Unit, enum ns2__formatType format, std::string &dwmlByDayOut)
{	struct ns1__NDFDgenByDayLatLonList soap_tmp_ns1__NDFDgenByDayLatLonList;
	struct ns1__NDFDgenByDayLatLonListResponse *soap_tmp_ns1__NDFDgenByDayLatLonListResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php";
	if (!soap_action)
		soap_action = "http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgenByDayLatLonList";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__NDFDgenByDayLatLonList.listLatLon = listLatLon;
	soap_tmp_ns1__NDFDgenByDayLatLonList.startDate = startDate;
	soap_tmp_ns1__NDFDgenByDayLatLonList.numDays = numDays;
	soap_tmp_ns1__NDFDgenByDayLatLonList.Unit = Unit;
	soap_tmp_ns1__NDFDgenByDayLatLonList.format = format;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__NDFDgenByDayLatLonList(soap, &soap_tmp_ns1__NDFDgenByDayLatLonList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__NDFDgenByDayLatLonList(soap, &soap_tmp_ns1__NDFDgenByDayLatLonList, "ns1:NDFDgenByDayLatLonList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__NDFDgenByDayLatLonList(soap, &soap_tmp_ns1__NDFDgenByDayLatLonList, "ns1:NDFDgenByDayLatLonList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&dwmlByDayOut)
		return soap_closesock(soap);
	soap_default_std__string(soap, &dwmlByDayOut);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__NDFDgenByDayLatLonListResponse = soap_get_ns1__NDFDgenByDayLatLonListResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	dwmlByDayOut = soap_tmp_ns1__NDFDgenByDayLatLonListResponse->dwmlByDayOut;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__GmlLatLonList(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::string listLatLon, time_t requestedTime, enum ns2__featureTypeType featureType, ns2__weatherParametersType *weatherParameters, std::string &dwGmlOut)
{	struct ns1__GmlLatLonList soap_tmp_ns1__GmlLatLonList;
	struct ns1__GmlLatLonListResponse *soap_tmp_ns1__GmlLatLonListResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php";
	if (!soap_action)
		soap_action = "http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#GmlLatLonList";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__GmlLatLonList.listLatLon = listLatLon;
	soap_tmp_ns1__GmlLatLonList.requestedTime = requestedTime;
	soap_tmp_ns1__GmlLatLonList.featureType = featureType;
	soap_tmp_ns1__GmlLatLonList.weatherParameters = weatherParameters;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__GmlLatLonList(soap, &soap_tmp_ns1__GmlLatLonList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__GmlLatLonList(soap, &soap_tmp_ns1__GmlLatLonList, "ns1:GmlLatLonList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__GmlLatLonList(soap, &soap_tmp_ns1__GmlLatLonList, "ns1:GmlLatLonList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&dwGmlOut)
		return soap_closesock(soap);
	soap_default_std__string(soap, &dwGmlOut);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__GmlLatLonListResponse = soap_get_ns1__GmlLatLonListResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	dwGmlOut = soap_tmp_ns1__GmlLatLonListResponse->dwGmlOut;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__GmlTimeSeries(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::string listLatLon, time_t startTime, time_t endTime, enum ns2__compTypeType compType, enum ns2__featureTypeType featureType, std::string propertyName, std::string &dwGmlOut)
{	struct ns1__GmlTimeSeries soap_tmp_ns1__GmlTimeSeries;
	struct ns1__GmlTimeSeriesResponse *soap_tmp_ns1__GmlTimeSeriesResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php";
	if (!soap_action)
		soap_action = "http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#GmlTimeSeries";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__GmlTimeSeries.listLatLon = listLatLon;
	soap_tmp_ns1__GmlTimeSeries.startTime = startTime;
	soap_tmp_ns1__GmlTimeSeries.endTime = endTime;
	soap_tmp_ns1__GmlTimeSeries.compType = compType;
	soap_tmp_ns1__GmlTimeSeries.featureType = featureType;
	soap_tmp_ns1__GmlTimeSeries.propertyName = propertyName;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__GmlTimeSeries(soap, &soap_tmp_ns1__GmlTimeSeries);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__GmlTimeSeries(soap, &soap_tmp_ns1__GmlTimeSeries, "ns1:GmlTimeSeries", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__GmlTimeSeries(soap, &soap_tmp_ns1__GmlTimeSeries, "ns1:GmlTimeSeries", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&dwGmlOut)
		return soap_closesock(soap);
	soap_default_std__string(soap, &dwGmlOut);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__GmlTimeSeriesResponse = soap_get_ns1__GmlTimeSeriesResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	dwGmlOut = soap_tmp_ns1__GmlTimeSeriesResponse->dwGmlOut;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__LatLonListSubgrid(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::string lowerLeftLatitude, std::string lowerLeftLongitude, std::string upperRightLatitude, std::string upperRightLongitude, std::string resolution, struct ns1__LatLonListSubgridResponse &_param_1)
{	struct ns1__LatLonListSubgrid soap_tmp_ns1__LatLonListSubgrid;
	if (!soap_endpoint)
		soap_endpoint = "http://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php";
	if (!soap_action)
		soap_action = "http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListSubgrid";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__LatLonListSubgrid.lowerLeftLatitude = lowerLeftLatitude;
	soap_tmp_ns1__LatLonListSubgrid.lowerLeftLongitude = lowerLeftLongitude;
	soap_tmp_ns1__LatLonListSubgrid.upperRightLatitude = upperRightLatitude;
	soap_tmp_ns1__LatLonListSubgrid.upperRightLongitude = upperRightLongitude;
	soap_tmp_ns1__LatLonListSubgrid.resolution = resolution;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__LatLonListSubgrid(soap, &soap_tmp_ns1__LatLonListSubgrid);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__LatLonListSubgrid(soap, &soap_tmp_ns1__LatLonListSubgrid, "ns1:LatLonListSubgrid", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__LatLonListSubgrid(soap, &soap_tmp_ns1__LatLonListSubgrid, "ns1:LatLonListSubgrid", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_1)
		return soap_closesock(soap);
	soap_default_ns1__LatLonListSubgridResponse(soap, &_param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__LatLonListSubgridResponse(soap, &_param_1, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__LatLonListLine(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::string endPoint1Lat, std::string endPoint1Lon, std::string endPoint2Lat, std::string endPoint2Lon, struct ns1__LatLonListLineResponse &_param_2)
{	struct ns1__LatLonListLine soap_tmp_ns1__LatLonListLine;
	if (!soap_endpoint)
		soap_endpoint = "http://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php";
	if (!soap_action)
		soap_action = "http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListLine";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__LatLonListLine.endPoint1Lat = endPoint1Lat;
	soap_tmp_ns1__LatLonListLine.endPoint1Lon = endPoint1Lon;
	soap_tmp_ns1__LatLonListLine.endPoint2Lat = endPoint2Lat;
	soap_tmp_ns1__LatLonListLine.endPoint2Lon = endPoint2Lon;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__LatLonListLine(soap, &soap_tmp_ns1__LatLonListLine);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__LatLonListLine(soap, &soap_tmp_ns1__LatLonListLine, "ns1:LatLonListLine", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__LatLonListLine(soap, &soap_tmp_ns1__LatLonListLine, "ns1:LatLonListLine", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_2)
		return soap_closesock(soap);
	soap_default_ns1__LatLonListLineResponse(soap, &_param_2);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__LatLonListLineResponse(soap, &_param_2, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__LatLonListZipCode(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::string zipCodeList, struct ns1__LatLonListZipCodeResponse &_param_3)
{	struct ns1__LatLonListZipCode soap_tmp_ns1__LatLonListZipCode;
	if (!soap_endpoint)
		soap_endpoint = "http://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php";
	if (!soap_action)
		soap_action = "http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListZipCode";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__LatLonListZipCode.zipCodeList = zipCodeList;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__LatLonListZipCode(soap, &soap_tmp_ns1__LatLonListZipCode);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__LatLonListZipCode(soap, &soap_tmp_ns1__LatLonListZipCode, "ns1:LatLonListZipCode", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__LatLonListZipCode(soap, &soap_tmp_ns1__LatLonListZipCode, "ns1:LatLonListZipCode", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_3)
		return soap_closesock(soap);
	soap_default_ns1__LatLonListZipCodeResponse(soap, &_param_3);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__LatLonListZipCodeResponse(soap, &_param_3, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__LatLonListSquare(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::string centerPointLat, std::string centerPointLon, std::string distanceLat, std::string distanceLon, std::string resolution, struct ns1__LatLonListSquareResponse &_param_4)
{	struct ns1__LatLonListSquare soap_tmp_ns1__LatLonListSquare;
	if (!soap_endpoint)
		soap_endpoint = "http://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php";
	if (!soap_action)
		soap_action = "http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListSquare";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__LatLonListSquare.centerPointLat = centerPointLat;
	soap_tmp_ns1__LatLonListSquare.centerPointLon = centerPointLon;
	soap_tmp_ns1__LatLonListSquare.distanceLat = distanceLat;
	soap_tmp_ns1__LatLonListSquare.distanceLon = distanceLon;
	soap_tmp_ns1__LatLonListSquare.resolution = resolution;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__LatLonListSquare(soap, &soap_tmp_ns1__LatLonListSquare);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__LatLonListSquare(soap, &soap_tmp_ns1__LatLonListSquare, "ns1:LatLonListSquare", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__LatLonListSquare(soap, &soap_tmp_ns1__LatLonListSquare, "ns1:LatLonListSquare", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_4)
		return soap_closesock(soap);
	soap_default_ns1__LatLonListSquareResponse(soap, &_param_4);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__LatLonListSquareResponse(soap, &_param_4, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__CornerPoints(struct soap *soap, const char *soap_endpoint, const char *soap_action, enum ns2__sectorType sector, struct ns1__CornerPointsResponse &_param_5)
{	struct ns1__CornerPoints soap_tmp_ns1__CornerPoints;
	if (!soap_endpoint)
		soap_endpoint = "http://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php";
	if (!soap_action)
		soap_action = "http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#CornerPoints";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__CornerPoints.sector = sector;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__CornerPoints(soap, &soap_tmp_ns1__CornerPoints);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__CornerPoints(soap, &soap_tmp_ns1__CornerPoints, "ns1:CornerPoints", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__CornerPoints(soap, &soap_tmp_ns1__CornerPoints, "ns1:CornerPoints", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_5)
		return soap_closesock(soap);
	soap_default_ns1__CornerPointsResponse(soap, &_param_5);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__CornerPointsResponse(soap, &_param_5, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__LatLonListCityNames(struct soap *soap, const char *soap_endpoint, const char *soap_action, enum ns2__displayLevelType displayLevel, struct ns1__LatLonListCityNamesResponse &_param_6)
{	struct ns1__LatLonListCityNames soap_tmp_ns1__LatLonListCityNames;
	if (!soap_endpoint)
		soap_endpoint = "http://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php";
	if (!soap_action)
		soap_action = "http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListCityNames";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__LatLonListCityNames.displayLevel = displayLevel;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__LatLonListCityNames(soap, &soap_tmp_ns1__LatLonListCityNames);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__LatLonListCityNames(soap, &soap_tmp_ns1__LatLonListCityNames, "ns1:LatLonListCityNames", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__LatLonListCityNames(soap, &soap_tmp_ns1__LatLonListCityNames, "ns1:LatLonListCityNames", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_6)
		return soap_closesock(soap);
	soap_default_ns1__LatLonListCityNamesResponse(soap, &_param_6);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__LatLonListCityNamesResponse(soap, &_param_6, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
